text = input("Введите текст: ")
new_text = text.replace(" ", "")
new_text = text.replace(".", "")
new_text = text.replace("!", "")
new_text = text.replace("?", "")
new_text = text.replace(",", "")
new_text = new_text.lower()
print("a: " + str(new_text.count('а')))
print("б: " + str(new_text.count('б')))
print("в: " + str(new_text.count('в')))
print("г: " + str(new_text.count('г')))
print("д: " + str(new_text.count('д')))
print("е: " + str(new_text.count('е')))
print("ё: " + str(new_text.count('ё')))
print("ж: " + str(new_text.count('ж')))
print("з: " + str(new_text.count('з')))
print("и: " + str(new_text.count('и')))
print("й: " + str(new_text.count('й')))
print("к: " + str(new_text.count('к')))
print("л: " + str(new_text.count('л')))
print("м: " + str(new_text.count('м')))
print("н: " + str(new_text.count('н')))
print("о: " + str(new_text.count('о')))
print("п: " + str(new_text.count('п')))
print("р: " + str(new_text.count('р')))
print("с: " + str(new_text.count('с')))
print("т: " + str(new_text.count('т')))
print("у: " + str(new_text.count('у')))
print("ф: " + str(new_text.count('ф')))
print("х: " + str(new_text.count('х')))
print("ц: " + str(new_text.count('ц')))
print("ч: " + str(new_text.count('ч')))
print("ш: " + str(new_text.count('ш')))
print("щ: " + str(new_text.count('щ')))
print("ъ: " + str(new_text.count('ъ')))
print("ы: " + str(new_text.count('ы')))
print("ь: " + str(new_text.count('ь')))
print("э: " + str(new_text.count('э')))
print("ю: " + str(new_text.count('ю')))
print("я: " + str(new_text.count('я')))

